### ISSUE TITLE
dep ensure takes ages

### ISSUE THREAD

**Issue by piotrkowalczuk** [travelaudience/aerospike-operator#6]
Due to dependency on `k8s.io/kubernetes` calling `make dep` takes a very long time (in fact it never finish). The only place where it is imported is `reconciler/podutils.go`. `IsPodReady` function is the only one that is used from the import. I believe it would be a good idea to copy this function to the codebase to reduce dependency tree.

**Comment by pires** [comment]
Let's wait on #7 to be merged then.

**Comment by pires** [comment]
Closed by #7.
